export const DISCORDIA_EVENTS = {
  HOME_BUTTON_CLICKED: 'DISCORDIA_HOME_BUTTON_CLICKED',
  ENTITY_DELETED: 'DISCORDIA_ENTITY_DELETED',
  CHAT_UPDATE: 'DISCORDIA_CHAT_UPDATE',
  ICONS_UPDATE: 'DISCORDIA_ICONS_UPDATE',
  ENTITY_CHANGED: 'DISCORDIA_ENTITY_CHANGED',
  CHAT_SWITCH_PENDING: 'DISCORDIA_CHAT_SWITCH_PENDING',
  EXTENSION_HTML_POPULATED: 'DISCORDIA_EXTENSION_HTML_POPULATED',
  EXTENSION_HTML_LATELOAD: 'DISCORDIA_EXTENSION_HTML_LATELOAD',
};
