export const DISCORDIA_EVENTS = {
  HOME_BUTTON_CLICKED: 'DISCORDIA_HOME_BUTTON_CLICKED',
  ENTITY_DELETED: 'DISCORDIA_ENTITY_DELETED',
  CHAT_UPDATE: 'DISCORDIA_CHAT_UPDATE',
  ICONS_UPDATE: 'DISCORDIA_ICONS_UPDATE',
  ENTITIES_LENGTH_CHANGED: 'DISCORDIA_ENTITIES_LENGTH_CHANGED',
};
